### ISSUE TITLE
Add library policies to e2e

### ISSUE THREAD

**Issue by ritazh** [open-policy-agent/gatekeeper-library#10]
Our e2e tests should test the policies in /library, especially for new constraints and constraint templates.

**Comment by gerasym** [comment]
Could anyone explain current expected dev flow? I can create src.rego and src_test.rego and run `opa test src.rego src_test.rego` to test it. But how can i test constraint template?

**Comment by maxsmythe** [comment]
That's a good question and one we've started working on answering!

The draft design for building a constraint template build/test workflow is here:

https://docs.google.com/document/d/1uQlkIBQcgNNyth8o9ufYaVSfUq_JLJGy9fcuW3VB7vU/edit

Definitely interested in feedback and help implementing :)
