### ISSUE TITLE
the k8scontainerratios policy only allows a fixed ratio for both cpu and memory resource limits

### ISSUE THREAD

**Issue by mvanholsteijn** [open-policy-agent/gatekeeper-library#107]
the k8scontainerratios policy allows you to specify the ratio between request and limit, but the ratio applies to both memory and cpu. I would like to specify a ratio op 1 for memory and a ratio of 4 for cpu so that we can overcommit on cpu, but not on memory.

**Comment by aliokaitis** [comment]
just add second option in properties and then reference to it "mem_ratio "

**Comment by mvanholsteijn** [comment]
I already made a pull request -> https://github.com/open-policy-agent/gatekeeper-library/pull/108
