### ISSUE TITLE
add rego policy for deny automountServiceAccountToken for Pod

### ISSUE THREAD

**Issue by developer-guy** [open-policy-agent/gatekeeper-library#136]
By default, every Pod has a service account assigned and has access to the API Server using the token created for this service account lives under the `/var/run/secrets/kubernetes.io/serviceaccount/token.` You can access the API from inside a pod using automatically mounted service account credentials.

So, it'd be worth disabling this feature by providing a Rego policy for it.

cc: @dentrax @sozercan

**Comment by developer-guy** [comment]
If you agree on this issue, would you mind assigning it to me? 😋

**Comment by sozercan** [comment]
fyi - you can also set `automountServiceAccountToken` in SA level:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server

if a pod is referencing a SA that has automountServiceAccountToken set, SA will need to be in OPA cache to be able to be queried.

**Comment by developer-guy** [comment]
> fyi - you can also set `automountServiceAccountToken` in SA level: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
> 
> if a pod is referencing a SA that has automountServiceAccountToken set, SA will need to be in OPA cache to be able to be queried.

yes I know @sozercan, I updated the title of the issue according to that, so, we can open a seperate issue for ServiceAccount, let's not include both of them to a single issue, WDYT?

**Comment by maxsmythe** [comment]
We should try to avoid over-stating what CTs are doing. Since k8s is ever-evolving, it may be that a previously thorough CT bit-rots due to additional config surface being added, but if we are aware of additional surface areas, we should try to highlight that.

In that vein, two questions:

* Should the CT be intent-based and cover all surface areas, at the cost of turning it into a referential constraint?
* If the answer to the above is "no", how do we broadcast the limits of this CT? Preferably in it's name as that's the most common thing people will see.

**Comment by ritazh** [comment]
I believe @fseldow worked on a CT for this to both look at the pod spec for `automountServiceAccountToken` and look at the volumeMount in containers for the `/var/run/secrets/kubernetes.io/serviceaccount` mountPath. This would alleviate the need to have a referential constraint. WDYT?

**Comment by maxsmythe** [comment]
If that alleviates the service account route for mounting tokens, I love it.

**Comment by fseldow** [comment]
Hi @developer-guy , thanks for contribution. I leave one comment on your PR. 
There is another issue https://github.com/Azure/azure-policy/issues/763, so I suggest to check volumeMount when `automountServiceAccountToken`  is nil on pod side.

I have one sample rego template from Azure Policy to solve this issue. Hope it may help.
https://store.policy.core.windows.net/kubernetes/block-automount-token/v1/template.yaml

Separating into two rego, one for pod and another for service account, may require user to apply both the rego at the same time. And might be too strict (all service account except 'default' need set automountServiceAccountToken=false)

**Comment by developer-guy** [comment]
amazing @fseldow thank you so much, I've updated the Rego policy according to your changes 🙋🏻‍♂️🤝
