### ISSUE TITLE
K8sRequiredAnnotations allow some applications

### ISSUE THREAD

**Issue by rafaeljesus** [open-policy-agent/gatekeeper-library#137]
How do I allow certain applications from being checked using K8sRequiredAnnotations?

With confest, I have a `policy.rego` that allows a particular app to pass if it misses the k8s `safe-to-evict` annotation:

`policy.rego`:

```rego
package main

missingAnnotationMsg :=`
The %s %s resource is missing:

spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "{{ .Values.safeToEvict }}"
`

resources := ["Deployment", "StatefulSet"]

default allow = false

allow {
	input.metadata.labels.app == "my-app"
}

deny[msg] {
	not allow
	input.kind == resources[_]

	not input.spec.template.metadata.annotations["cluster-autoscaler.kubernetes.io/safe-to-evict"]

	msg := sprintf(missingAnnotationMsg, [
		input.metadata.labels.app,
		input.kind,
	])
}
```

I simply run `helm template my-app | conftest test --policy policy.rego -` and it allows my-app as desired,

Is there a way to achieve similar behaviour with `K8sRequiredAnnotations`? If it doesn't, how can I create such a rule?

Thanks

**Comment by maxsmythe** [comment]
You would use a label selector (`spec.match.labelSelector`):

https://open-policy-agent.github.io/gatekeeper/website/docs/howto/#constraints

We should probably have better documentation for label selector's schemas. I'm not aware of any K8s docs where they explicitly document the schema, but here is where we define it, and it does have some docstrings:

https://github.com/open-policy-agent/gatekeeper/blob/1540d5b94e06d0c2f7c4b78e5c7b1d3167c24cb3/pkg/target/target.go#L290-L336

One caveat about the idea of using labels for exemptions: labels are not ACLd. This means anyone can apply a `metadata.labels.app` label and claim your exemption. If this matters to you, you'll probably need to lock down the label in some manner.

**Comment by maxsmythe** [comment]
Also, to limit your search a bit more, `spec.match.labelselector.matchExpressions`, and you want the `NotIn` operator.
