### ISSUE TITLE
Allow images with valid image signature via notary v2 or sigstore/cosign Mutate image tag to use sha

### ISSUE THREAD

**Issue by Anil-kattoju** [open-policy-agent/gatekeeper-library#139]
Allow images with valid image signature via notary v2 or sigstore/cosign
-Mutate image tag to use sha
-Validate image signature

Any policy in-place above requirement?

**Comment by sozercan** [comment]
@Anil-kattoju this is work in progress for both.

Cosign: https://github.com/sigstore/cosign/issues/655
Ratify/Notary v2: https://github.com/deislabs/ratify
