### ISSUE TITLE
Is there a way to allow certain apps in K8sRequiredAnnotations?

### ISSUE THREAD

**Issue by rafaeljesus** [open-policy-agent/gatekeeper-library#140]
Is there a way I tell [K8sRequiredAnnotations](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/requiredannotations/samples/all-must-have-certain-set-of-annotations/constraint.yaml) to allow certain resources? like, I want to enforce the k8s `safe-to-evict` annotation is present in certain pods, but not all of them, I saw the excludeNamespaces field, but it doesn’t address my use case, thoughts? thanks

**Comment by maxsmythe** [comment]
What criteria are you using to determine whether a given pod is exempt from the rules?

A common challenge with exemptions is writing them in a way such that malicious users can't take advantage of them. For example, if I exempt via the existence of a label, what prevents a malicious user from using that label? Unless that concern is moot (for example, all things with an "untrusted" label are isolated from secure systems, so mounting as root is fine), whatever exclusion criteria is used should be locked down such that the only way to have that exception is where it's expected.
