### ISSUE TITLE
Add documentation on testing constraint framework

### ISSUE THREAD

**Issue by trissanen** [open-policy-agent/gatekeeper-library#142]
The library contains test suite definitions like https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/allowedrepos/suite.yaml

Could you please add documentation on how to use these resources?

**Comment by maxsmythe** [comment]
Thanks for asking!

The runner for the test suite is currently in development (nearing alpha, I think)? IIRC we are working on documentation.

@willbeason

**Comment by willbeason** [comment]
Yep, now that the binary is officially released I can make documentation point to all of this. The docs will live in the gatekeeper repository, but it's probably not a bad idea for me to go back and add a link to those docs from gatekeeper-library.

**Comment by sozercan** [comment]
ref https://github.com/open-policy-agent/gatekeeper/issues/1600
