### ISSUE TITLE
Make Suites into valid KRM resources

### ISSUE THREAD

**Issue by rahuldhir** [open-policy-agent/gatekeeper-library#156]
Hi, I am using kpt to manage my Kubernetes configuration and am trying to use the `library/` folder in this repo as an upstream kpt package. I am only interested in pulling down the `ConstraintTemplate` resources into my local kpt package, so I have added a kpt function that removes all KRM resources that don't match the `ConstraintTemplate` kind. When running my kpt function pipeline, I receive the following error:
```
> kpt fn render --output=stdout .
Package "gatekeeper-library/general":
Error: input resource list must contain only KRM resources: allowedrepos/suite.yaml: resource must have `metadata.name`
```

It appears the `suite.yaml` files used by the gator CLI are not valid KRM resources due to this missing field so the kpt function orchestrator returns this error before my function even runs.

Is it possible to set `metadata.name` on the Suite resources? I have not contributed to this repo before but I am willing to open a PR to make this change. If there is a different pattern you recommend for using kpt to fetch the `ConstraintTemplate` resources, please let me know.

**Comment by maxsmythe** [comment]
Sorry that broke your kpt pipeline :/

It should be possible to add metadata.name values to the Suites. @willbeason any reason this isn't the case?

**Comment by willbeason** [comment]
On our end, there's no reason to reject a suite file just because it doesn't have a name. We don't use that field, so having validation for it doesn't make sense (why add an unnecessary hurdle?). It's perfectly fine to just add that field to any suite files you write.

**Comment by maxsmythe** [comment]
Would we not benefit from suite names? For instance, for writing human-readable output in the case where we having multiple suites?

FWIW breaking kpt is a fairly large issue, since it's probably the easiest way to keep library packages up-to-date.

**Comment by maxsmythe** [comment]
We could just add `name` to the library suite yamls, but there is some value in making sure it's a universal standard.

**Comment by willbeason** [comment]
Added bug to gator beta milestone: https://github.com/open-policy-agent/gatekeeper/issues/1756

Defining the requirements for making Suites into fully following the KRM model is nontrivial, so rather than an immediate fix I'd rather make this an explicit work item. Discussion of requirements will be in the linked issue.
