### ISSUE TITLE
Exempting by resource in a namespace

### ISSUE THREAD

**Issue by aligabres** [open-policy-agent/gatekeeper-library#159]
Hello,

Do we have something in the road-map to allow exempting a non-compliance by resource instead of by namespace? I'd like to be more targeted. 

For example, currently, if a pod is non-compliant with a specific GKE CIS benchmark control, we can only exempt the entire namespace from that control which in turn exempts all the other pods in that namespace

Thanks.

**Comment by maxsmythe** [comment]
You can use label selectors for this, though I'd suggest locking down the label so it only applies to the pod of interest.

**Comment by aligabres** [comment]
Thanks Max,

Essentially a label attached to a pod that Gatekeeper references for exemption?

By extension, that would mean that anyone could exempt their pod/resource just by attaching a label?

**Comment by maxsmythe** [comment]
@aligabres Sorry, I lost this thread, but yes.

The ability for people to self-exempt is why it'd be good to have a second policy to limit where/when the label can be set.
