### ISSUE TITLE
Support for Wildcard Namespace Value

### ISSUE THREAD

**Issue by brec** [open-policy-agent/gatekeeper-library#165]
Hi,

I'm trying to create a policy that should apply to all namespaces. I've tried using a wildcard for the namespace value, but that's rejected:
```
The K8sAllowedRepos "repo-is-openpolicyagent" is invalid: spec.match.namespaces: Invalid value: "*": spec.match.namespaces in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\*|-\*)?$'
```

Example of the constraint config: 
```apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: repo-is-openpolicyagent
  namespace: gatekeeper-system
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    namespaces:
    - "*"
  ```

Alternatively, is there a supported way of applying a policy to all namespaces that perhaps doesn't use the wildcard function? I've also tried an empty string - "" to no avail.

**Comment by ritazh** [comment]
Hi @brec, if you want the constraint to be applied for all namespaces, then you can remove “namespaces”. “namespaces” is great for when you only want to apply a constraint to some of the namespaces by providing the full name or a prefix-based glob. PTAL https://open-policy-agent.github.io/gatekeeper/website/docs/howto#constraints

**Comment by brec** [comment]
Thanks @ritazh  I missed that in the documentation. Thanks for pointing it out. I'll close this.
