### ISSUE TITLE
Organization of the library

### ISSUE THREAD

**Issue by sozercan** [open-policy-agent/gatekeeper-library#169]
We need a discussion to evaluate different proposals for how to organize CT/Constraint, mutation, external data. Looking for someone to help drive this.

**Comment by g-awmalik** [comment]
Couple of proposals here: https://docs.google.com/document/d/11qID7yGpPU2ZPziqRxYYSHoxij514Aq9ChmlIs9Ysus. We can discuss further during our meetup.
