### ISSUE TITLE
keep constraint template api version in release branches or tags

### ISSUE THREAD

**Issue by maratsal** [open-policy-agent/gatekeeper-library#181]
It is more like suggestion and not the issue.

I have faced this problem when I tried to deploy constraint templates of api v1 to recent OpenShift deployment with deployed gatekeeper operator and realized that operator doesn't support v1 of constraint template yet.

Therefore I thought it might be a good idea to keep older versions (v1alpha1, v1beta1) of constraint templates in some release branches or tags?

**Comment by fuog** [comment]
i can only support this proposal. We normally also work with tags and test accordingly whether newer versions of a repo that we source are also compatible with our infrastructure. Latest is not always greatest. at least not uncontrolled.

**Comment by ritazh** [comment]
Currently the version of a constraint template is annotated by metadata.gatekeeper.sh/version: 1.0.0.  An API bump would result in a major version bump per guidelines described in https://open-policy-agent.github.io/gatekeeper-library/website/#new-policy. However this versioning guideline was introduced after the most recent API bump to v1. For future API bumps we can update the version annotation and cut a tag.
