### ISSUE TITLE
storage class required

### ISSUE THREAD

**Issue by kfox1111** [open-policy-agent/gatekeeper-library#183]
We have clusters that have several storage classes. We don't have a default storage class as its not easy to choose one. We want the users to think about which one they need. But things break in annoying ways if no default is defined. So:

It would be nice if there was a policy in the library that rejected statefulsets/pvc's that did not have a storage class defined. Bonus points for responding with a list of valid options when it does so.

**Comment by kfox1111** [comment]
Done here: https://github.com/open-policy-agent/gatekeeper-library/pull/214

**Comment by maxsmythe** [comment]
Awesome! Closing.
