### ISSUE TITLE
Check Pod policies on Deployments

### ISSUE THREAD

**Issue by markszabo** [open-policy-agent/gatekeeper-library#186]
We are using these policies on our kubernetes cluster, however we often run into the following situation:

1. Create a PR with a change to an app (including the kubernetes yamls)
2. Run the pipeline that runs `kubectl apply --dry-run=server`, which also evaluates the validating webhooks including gatekeeper. This passes
3. PR is merged
4. The deploy pipeline succeeds and updates the `Deployment`
5. Gatekeeper prevents the creation of the new `Pods` as they go against some of the policies
6. We have to send a new PR fixing the policies, which can only be tested after merge

**Desired state:** The pipeline should fail on a PR already if any of the policies are violated

Since the policies are only checked against `Pods`, but the PR contains `Deployments`, this situation often repeats itself. The same problem can happen with other [workload resources that create pods](https://kubernetes.io/docs/concepts/workloads/controllers/).

Is there a solution or workaround for this problem?

One idea we have is to evaluate all policies defined for `Pod`'s `.spec` against `Deployment`'s `spec.template.spec`, but that would require changes to these policies, which would make it hard to keep them updated. Also I feel that this must be a common problem, so I'd prefer to find a solution that can be used by others easily too (e.g. if we end up making this change, we are happy to send a PR with them).

**Comment by markszabo** [comment]
I had some time and I think a simple change to the policies could make this possible. For example for [allowedrepos](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/allowedrepos/template.yaml):

```rego
package k8sallowedrepos

containers[c] {
  input.review.object.kind == "Pod"
  c := input.review.object.spec.containers[_]
}

containers[c] {
  input.review.object.kind == ["Deployment", "ReplicaSet", "StatefulSet", "DaemonSet", "Job", "ReplicationController"][_]
  c := input.review.object.spec.template.spec.containers[_]
}

containers[c] {
  input.review.object.kind == "CronJob"
  c := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
}

violation[{"msg": msg}] {
  container := containers[_]
  satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(container.image, repo)]
  not any(satisfied)
  msg := sprintf("container <%v> has an invalid image repo <%v>, allowed repos are %v", [container.name, container.image, input.parameters.repos])
}
```

(and then of course the same for initContainers.)

I'm happy to prepare a PR with these, if you are willing to give this idea a shot.

**Comment by ritazh** [comment]
@markszabo Thanks for raising this! We are looking at a [design](https://docs.google.com/document/u/0/d/1wsTnP0IYNcwVxy7XVs8WRv4WUhJZPJl_RdVZaGd5LNc/mobilebasic#) to support workload resource validation. Would love your thoughts on it. In the meantime, can you see [the gator test cli cmd](https://open-policy-agent.github.io/gatekeeper/website/docs//gatekeeper/website/docs/gator) can help?

**Comment by maxsmythe** [comment]
It's actively being worked on. I don't want to project a date, but here is a PR that is starting the work stream:

https://github.com/open-policy-agent/gatekeeper/pull/2062

Once that gets submitted, the next step would be to add the capability to the webhook.
