### ISSUE TITLE
Request: Changelog and/or versioned releases

### ISSUE THREAD

**Issue by mac-chaffee** [open-policy-agent/gatekeeper-library#187]
Could we start doing versioned releases or tracking important changes in a changelog?

Since we don't have versioning, I believe we're left with two bad options when it comes to making backwards-incompatible changes: 

1. Just merge the change silently, like past changes to the CRDs
2. Just avoid making backwards-incompatible changes all together

If there was a changelog and a versioning strategy, we could make backwards-incompatible changes by incrementing the major version and including docs for migrating in the release notes/changelog. For example, if we ever find a security bug in the PSP constraints that was accidentally allowing stuff, it would not be backwards-compatible to fix that bug. Additionally, unless you search through PRs manually, users may not even know they ought to upgrade.

Interested in your thoughts on this since this would involve more stuff for maintainers to deal with 😅

**Comment by sathieu** [comment]
Can this be reopened?

At least a monthly tag would be an improvement ...

**Comment by ritazh** [comment]
We currently follow this versioning guideline for each policy in this library. Does this meet your needs or are you looking for something else?

> [Versioning](https://docs.google.com/document/d/1IYiypA-mRcdfSVfmoeyuaeG8XtA1u4GkcqH3kEkv2uw/edit) has been introduced for Gatekeeper Library policies. Please make sure to add or bump the version of the policy as per the guidelines in the src/<policy-name>/constraint.tmpl annotation.
Major version bump required: Whenever there is a breaking change in the policy e.g. updating template Kind, updating existing parameter schema, adding the requires-sync-data annotation to sync new data, or any other breaking changes
Minor version bump required: Whenever there is a backward compatible change in the policy e.g. adding a parameter, updating Rego logic
Patch version bump required: Whenever there is a simple backward compatible change in the policy, e.g. Simple Rego fix, updating policy metadata
Note: Sample constraints, mutations, and expansion templates are provided as examples, and severable changes do not require a version bump.

**Comment by sathieu** [comment]
@ritazh We are using GitOps (ArgoCD) and clone the whole repo and use kustomize on it. So we need versioning on the whole repo.

**Comment by sathieu** [comment]
Also we are using renovate and it has no way to retrieve version from Gatekeeper policies stored on artifacthub.
