### ISSUE TITLE
Testing userInfo constrainttemplates with gator

### ISSUE THREAD

**Issue by wmuizelaar** [open-policy-agent/gatekeeper-library#199]
Hi,

I'm currently writing a constrainttemplate that looks at the username, to make sure specific users (or service-accounts in my case) are exempt from certain policies. That all works well, but I'd also like to be able to test such a template with `gator verify`. But how do I supply userinformation in my `suite.yaml` so I can verify whether it actually works or not?

**Comment by avsthiago** [comment]
Woah, I'm just now searching for the exact same thing!

I'll post here if I find anything relevant.

**Comment by wmuizelaar** [comment]
Right, this is the wrong repo for that, so https://github.com/open-policy-agent/gatekeeper/issues/1819 asks basically what we need. Closing again ;-)
