### ISSUE TITLE
Policy is not enforced while updating

### ISSUE THREAD

**Issue by aamirali-dev** [open-policy-agent/gatekeeper-library#217]
I wanted to use these templates so I deployed them on the test cluster and tested if it works. I installed the gatekeeper using the helm. The very serious issue I'm facing is that policy is enforced while creating resources but it isn't enforced while updating resources. 
Example1:
if I set the replica limit max to 8, I can't create a deployment with 10 replicas but I can create a deployment with 5 replicas and scale it to 10 easily
Example2:
if I set the allowed repo to registry.aamir.ch then I'm not allowed to create deployments with --image=nginx but what I can do is create deployments with image=registry.aamir.ch/nginx but then I can update the image to Nginx

**Comment by maxsmythe** [comment]
Example 1 could be this issue:

https://github.com/open-policy-agent/gatekeeper/issues/1837#issuecomment-1112156109

Example 2:

Can you show:

* the contents of the constraint and template that are meant to enforce the policy
* the shell transcript of this happening for potential reproduction

Enforcement on update is expected to work.

**Comment by aamirali-dev** [comment]
Example 2 is OK.
It is not showing the error and the image name is updated in deployment but UP-TO-DATE pods are zero.  I think it is working though I was expecting an error message

**Comment by maxsmythe** [comment]
> though I was expecting an error message

The constraint is enforced against Pods, which means deployments would not show an error message/rejection.

The below PR would add an ability to reject "generator" resources, but note that that is essentially mocking the behavior of other controllers and mutation webhooks, and as such can never be 100%:

#2062
#2229

glad everything's working! Feel free to re-open if there is anything more.
