### ISSUE TITLE
Unused parameter in one of the PodDisruptionBudget constraint messages

### ISSUE THREAD

**Issue by wjam** [open-policy-agent/gatekeeper-library#239]
The [validation message for one of the PodDisruptionBudget checks](https://github.com/open-policy-agent/gatekeeper-library/blob/36c420b5d40a65cb8d901b1a90ac996566a0af5b/src/general/poddisruptionbudget/src.rego#L33-L34) doesn't make use of the final parameterm, and so ends up being rendered like `Deployment <bar-app> has 1 replica(s) but PodDisruptionBudget <bar-app> has minAvailable of 1, PodDisruptionBudget count should always be lower than replica(s), and not used when replica(s) is set to 1%!(EXTRA int=1)`.

The final `obj.spec.replicas` should probably just be removed?

**Comment by ritazh** [comment]
Hi @wjam If I’m understanding you correctly, I think you are asking when is “obj.spec.replicas” being used in this policy? It is checked here to ensure the replica is always greater than the pdb: https://github.com/open-policy-agent/gatekeeper-library/blob/36c420b5d40a65cb8d901b1a90ac996566a0af5b/src/general/poddisruptionbudget/src.rego#L43
