### ISSUE TITLE
OpenShift Constraints Category

### ISSUE THREAD

**Issue by ctrought** [open-policy-agent/gatekeeper-library#240]
Would the [gatekeeper-library ](https://github.com/open-policy-agent/gatekeeper-library) repo owners be interested in having a category for OpenShift policies (ie. library/openshift) and accept PRs for it?

**Comment by sozercan** [comment]
@ctrought can you provide some examples of policies that would apply to OpenShift (but not general Kubernetes)?

**Comment by ctrought** [comment]
> @ctrought can you provide some examples of policies that would apply to OpenShift (but not general Kubernetes)?

A few examples

1. Require TLS on OpenShift Routes (Different than Ingress)
2. Require unique OpenShift Route hostname across namespaces unless permitted
  - Out of box this is already true and using hostnames [across namespaces is not enabled](https://docs.openshift.com/container-platform/4.10/networking/routes/route-configuration.html#nw-route-admission-policy_route-configuration). But with a custom policy you could allow sharing a hostname across specific namespaces if the namespaces were annotated with the hostname as a flag to allow it
3. Require unique SCC UID ranges for all namespaces (by default it's true, but if a user can patch/update a namespace they can overwrite the SCC UID range)
4. Disallow imagestreamtag that are [scheduled](https://docs.openshift.com/container-platform/4.10/openshift_images/image-streams-manage.html#images-imagestream-import_image-streams-managing)
5. Disallow imagestreamtag if the ref image size is greater than X MiB
6. Disallow imagestreamtag is dockerImageMetadata created date is older than X days/months
7. Enforce etcd encryption
