### ISSUE TITLE
Replicalimits constraint does not work for kubectl scale CLI

### ISSUE THREAD

**Issue by sota0113** [open-policy-agent/gatekeeper-library#250]
Hi, I have a question to limit replica pods.
`replicalimits` constraint works fine when I deploy pods with manifest file.
But `kubectl scale deploy ${DEPLOYMENT}  --replicas=${NUM}` can scale pods more than its limit.
Is this due to the nature of K8s admission webhook design?
Are there any means to limit replica pods deployed with `kubectl scale`?

**Comment by maxsmythe** [comment]
`kubectl scale` hits a separate subresource (which I think we do listen to by default). TBH I'm not sure what the contents of the scale admission request would look like (including the Kind). It might be worth trying to dump the request contents:

https://open-policy-agent.github.io/gatekeeper/website/docs/debug
