### ISSUE TITLE
Create allowed_example.yaml for every constraint

### ISSUE THREAD

**Issue by ctab** [open-policy-agent/gatekeeper-library#26]
In the [demo](https://github.com/open-policy-agent/gatekeeper/tree/master/demo) directory in the gatekeeper repo we have examples of good (allowed by constraint) resources as well as bad (not allowed by constraint). We should have these for the constraints in this repo also. Besides serving as additional illustration they help serve as the basis for integration testing.

**Comment by sozercan** [comment]
this is done, closing
