### ISSUE TITLE
K8spspallowprivilegeescalationcontainer - does not handle case where securityContext set at pod level?

### ISSUE THREAD

**Issue by pankajmt** [open-policy-agent/gatekeeper-library#263]
Newish to OPA Gatekeeper and its PSP replacement Policies

Looks like K8spspallowprivilegeescalationcontainer constraint template does not handle the case where the securityContext is not set at the container level but set at the pod level. As per https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod, it can be set at the pod level. 

```To specify security settings for a Pod, include the securityContext field in the Pod specification. The securityContext field is a [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#podsecuritycontext-v1-core) object. The security settings that you specify for a Pod apply to all Containers in the Pod.```

Am I reading this right? If so, looks like it needs to be enhanced? Still learning rego to be able to quickly do a PR for this!

A sample run against a Pod Spec with this scenario
<img width="961" alt="image" src="https://user-images.githubusercontent.com/32150474/206053773-fc60b14d-cbf1-4365-9b06-896aa7af1b53.png">

**Comment by maxsmythe** [comment]
Thanks for reaching out!

It looks like the pod security context and container security context objects are slightly different.

Pod-level: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#podsecuritycontext-v1-core

Container-level: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#securitycontext-v1-core

It appears only the container-level object has the `privileged` field, so it doesn't look like the pod security context is relevant for this specific rule.

A fun example of a template with lots of potential sources of truth would be the seccomp profile:

It can exist at either the pod level or the container level, and as either an annotation or as a config (depending on K8s version): https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/seccomp/template.yaml

**Comment by maxsmythe** [comment]
Good question. I'm not sure, though this PSP doc would seem to suggest undefined != true:

https://v1-24.docs.kubernetes.io/docs/concepts/security/pod-security-policy/#privilege-escalation

@sozercan do you know?

**Comment by sozercan** [comment]
This one is pretty complex, it defaults to true or false depending on other settings.

https://github.com/kubernetes/design-proposals-archive/blob/main/auth/no-new-privs.md#changes-of-securitycontext-objects

**Comment by pankajmt** [comment]
Its very complex indeed, and I have struggled to get my head around this fully. 

So back to the question still, should this constraint really fail when no securityContext is set at a container level? In our setup, I have come across couple of prometheus components (kube-state-metrics, node-exporter, prometheus-config-reloader), and one k8s backup tool (velero) which OOTB create pod manifests without securityContext for the container. and then i will either need to exempt those images or find a way to patch those manifests!

**Comment by pankajmt** [comment]
In the meantime I have figured out the Gatekeeper way to patch those manifests using Assigns!
