### ISSUE TITLE
Build script to insert src.rego into template.yaml files

### ISSUE THREAD

**Issue by ctab** [open-policy-agent/gatekeeper-library#27]
Per the [tooling proposal doc](https://docs.google.com/document/d/1uQlkIBQcgNNyth8o9ufYaVSfUq_JLJGy9fcuW3VB7vU/), we should set up a build script to automatically insert/update the Rego source in template.yaml files from the original src.rego. (We will need to update the README.md with instructions to run this script after any Rego code updates.)

The script should ideally also insert a version annotation (e.g. the SHA256 hash of the Rego code) which would let users know if the template they are using is current with the repo.

**Comment by ctab** [comment]
I've been working on this and should be able to submit it early next week.

**Comment by JonnieDoe** [comment]
I suggest to use: https://github.com/plexsystems/konstraint
