### ISSUE TITLE
PSP-Rules exemption based on Label or Annotations or deployment

### ISSUE THREAD

**Issue by raviranjanelastisys** [open-policy-agent/gatekeeper-library#288]
There are certain PSP rules where the `exemptImages` is not defined in constraint templates and so we have to exclude the  `namespace`  instead at the pod/container layer !! Ex- https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-namespaces/template.yaml#L37 . But we don't want to exclude the namespace but want to restrict at the pod level.

Below are the PSP-rules we might have to exclude `namespace`  based on current PSP-template defined but we don't want and should be excluded at the pod level !

**HostPID - https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-namespaces/template.yaml#L37
HostIPC - https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-namespaces/template.yaml#L40
VOLUMES - https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/volumes/template.yaml**

Is it possible to exclude above policy based on `exemptImages` function rather then excluding the namespace ? how can we restrict at the pod layer ?  Maybe use Label, annotations , deployment ways . ?

**Comment by maxsmythe** [comment]
`exemptImages` was written to exempt specific images from policies that are enforced on a per-image basis, which allows users to exempt injected sidecars.

The policies you're citing are for pod-wide configs, so probably don't map to that intent.

One idea would be to use a label selector match criteria to exempt any pods with the `exempt-from-enforcement` label on it, then add a second constraint that only allows that label to be set if the pod matches the necessary criteria (e.g. all the images are privileged images).
