### ISSUE TITLE
Unit testing script

### ISSUE THREAD

**Issue by ctab** [open-policy-agent/gatekeeper-library#29]
It would be good to have a script to run all of the src.rego and src_test.rego files from each policy directory through`opa test` to ensure everything passes.

**Comment by ctab** [comment]
I should be able to add this early next week.

**Comment by sozercan** [comment]
we have https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/test.sh currently, but it doesn't run in CI

**Comment by sozercan** [comment]
this is done, closing
