### ISSUE TITLE
Constraint to block deployment of pods with containers having either `stdin: true` or `tty: true`

### ISSUE THREAD

**Issue by tspearconquest** [open-policy-agent/gatekeeper-library#306]
I want to block the deployment of pods where any container has either `stdin: true` or `tty: true` and I've written a constraint for this purpose, so I'm filing this issue to highlight #305

**Comment by tspearconquest** [comment]
Not stale

**Comment by tspearconquest** [comment]
Not stale, pull request has been pending review for months. Can anyone approve it and merge please?

**Comment by maxsmythe** [comment]
Sorry, re-pinged the PR for a review as well.

**Comment by tspearconquest** [comment]
Not stale

**Comment by tspearconquest** [comment]
Not stale, the PR still needs review.

**Comment by tspearconquest** [comment]
Still pending review.

**Comment by ritazh** [comment]
@tspearconquest which PR are you blocked by?
https://github.com/open-policy-agent/gatekeeper-library/pull/305 has been merged.

**Comment by tspearconquest** [comment]
Apologies, I was mistaken.
