### ISSUE TITLE
New policies are added to the wrong path on the website

### ISSUE THREAD

**Issue by ritazh** [open-policy-agent/gatekeeper-library#314]
https://github.com/open-policy-agent/gatekeeper-library/tree/master/website/docs

ephemeralstoragelimit and horizontalpodautoscaler should be added to validation not root

**Comment by ritazh** [comment]
@nilekhc

**Comment by nilekhc** [comment]
I'll work on this

**Comment by nilekhc** [comment]
@ritazh I did not find any evidence to show that our script has a bug that might be creating files in the wrong directory. However, I have opened a PR to add validation to ensure that the directory structure is valid and as expected. PTAL when you get a chance.

cc @maxsmythe @sozercan

**Comment by ritazh** [comment]
xref #299
