### ISSUE TITLE
gatekeeper and PSS

### ISSUE THREAD

**Issue by caduceus4** [open-policy-agent/gatekeeper-library#342]
Hi,

I am new here. Trying to find the best way to implement Pod Security Standards within Gatekeeper, as opposed to the PSS included as part of K8S 1.25, so as to provide more specific exceptions and exclusions other than whole namespaces  that I can do with the PSS in K8s itself. Is there any way to do this, or perhaps I am going about this the wrong way? Are there any predefined constraints and templates available for PSS (Restricted, Baseline, and Privileged), for a given CIS/PSS release?

kyverno seems to have something for this at https://kyverno.io/policies/pod-security/ but I have not yet found something for Gatekeeper.

Any info would be appreciated. Thank you.

**Comment by wibed** [comment]
@Markieta id like to include those into gatekeeper, where do i find the crd's matching the constraints defined?

or even better, can you provide a quick line up on how to include this?

**Comment by Markieta** [comment]
The `gke-policy-library` constraints linked above (`pss-baseline-v2022`, `pss-restricted-v2022`) have all of `kind`s defined by templates in [`gatekeeper-library/library/pod-security-policy/`](https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy), therefore:

1. [Install Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/install/)
2. [Install `gatekeeper-library` templates via `kustomize` or `kubectl`.](https://github.com/open-policy-agent/gatekeeper-library/tree/master?tab=readme-ov-file#usage)
3. Install Google's PSS constraints (see "Apply the policy constraints with kubectl:" in `README.md`) ([pss-restricted-v2022](https://github.com/GoogleCloudPlatform/gke-policy-library/tree/main/anthos-bundles/pss-restricted-v2022#apply-the-policy-constraints-with-kubectl), [pss-baseline-v2022](https://github.com/GoogleCloudPlatform/gke-policy-library/tree/main/bundles/pss-baseline-v2022#apply-the-policy-constraints-with-kubectl))
