### ISSUE TITLE
Apply constraints for immutable fields only to CREATE operations

### ISSUE THREAD

**Issue by ordovicia** [open-policy-agent/gatekeeper-library#346]
## Problem

Constraint templates for immutable fields (e.g. `K8sPSPHostFilesystem` validates pods' volumes) are enforced for `UPDATE` operations when the Gatekeeper's validating admission webhook is configured to be applied to `UPDATE` operation.
This can cause the following situation:

1. Assume that a `K8sPSPHostFilesystem` constraint with `allowedHostPaths: [{ pathPrefix: "/app" }]` is on a cluster
2. A user creates a job, which creates a pod with `/app` host path volume
3. An administrator removes `/app` path prefix from `allowedHostPaths` of the `K8sPSPHostFilesystem` constraint
4. The user deletes the job, which in turn makes the job controller tries to updates the pod's finalizers
5. The pod's finalizers cannot be updated because the pod has `/app` host path volume and it now voilates the `K8sPSPHostFilesystem` constraint
6. The `/app` host path volume also cannot be removed from the pod, because pods' volume config is immutable.
7. As a result, the pod stuck in Terminating phase

## Possible solution 1

Configuring the Gatekeeper's validating webhook to be applied only to `CREATE` operation.

This solution cannot be adopted if a cluster has constrains for mutable fields (e.g. `K8sRequiredLabels`).

## Possible soultion 2

Modifying constraints templates for immutable fields to be applied only to `CREATE` operation.

This solution can be implemented by adding a `input.review.operation` condition to constraint definitions written in Rego.

What do you think?

**Comment by ordovicia** [comment]
Thank you for your swift comment!
Excluding `UPDATE` operation in the minimum range seems good.
I am going to create a PR on that plan.

**Comment by maxsmythe** [comment]
Related issue (which reaches no conclusions):

https://github.com/open-policy-agent/gatekeeper/issues/1520

**Comment by ordovicia** [comment]
I created PR #348 that would fix this issue.

**Comment by maxsmythe** [comment]
Sorry for the delay in reviewing. @apeabody does the PR LGTY?

**Comment by maxsmythe** [comment]
It would also be good to have a general solution to the "need to remove a finalizer" problem.

**Comment by apeabody** [comment]
> Sorry for the delay in reviewing. @apeabody does the PR LGTY?

Thanks @maxsmythe! The basics look good, I just had a question on the inclusion of "PATCH", and we should probably include template level test coverage of the new behavior.  https://github.com/open-policy-agent/gatekeeper-library/pull/348#pullrequestreview-1548049177

**Comment by ordovicia** [comment]
#348 will fix this issue.
