### ISSUE TITLE
k8spsphostnetworkingports exemptImages does not allow hostNetwork

### ISSUE THREAD

**Issue by whs** [open-policy-agent/gatekeeper-library#460]
The k8spsphostnetworkingports policy do not allow a pod that contains `exemptImage` to use `hostNetwork`.

I believe it should either

1. Documented. A similar policy is k8spsphostfilesystem which validate pod-level volumes do not support this feature and do not have `exemptImages` parameter.
2. If one of the containers is exempt, then the whole pod can set hostNetwork to any value.

**Comment by whs** [comment]
I already did completed 2 internally, I'll submit a PR.

What do you say if I submitted k8spsphostfilesystem exemptImages support as well? I'm not sure what was the reason it did not support exemptImages initially.

**Comment by maxsmythe** [comment]
I do not think we want to do (2) as it opens up a security hole. The fact that an exempt sidecar can be injected (say an istio sidecar) would nullify the policy for the whole pod. This means a malicious user would be able to give a malicious image access to the host network. This would be a surprising behavior for users that renders the policy ineffective.

Additionally, this would be a backwards-incompatible change, necessitating a version bump.

I'd prefer either (1), or adding a parameter that gives the behavior of (2), explicitly documenting the downsides.
