### ISSUE TITLE
Releasing of Gatekeeper-Library

### ISSUE THREAD

**Issue by FabiusE** [open-policy-agent/gatekeeper-library#47]
It would be nice if the Gatekeeper-Library would have a release like a semantic release.

I'm about to implement Gatekeeper and a set of Libs at a Kubernetes Cluster using a GitOps approach with ArgoCD.
I would like to be able to install the Gatekeeper-Library directly from the GitHub Repo but if I point my ArgoCD to the GitHub Repo to install the wanted libs, I will automatically get every update of the Library which could damage the integrity of the services running inside the K8S-Cluster. 
The alternative is to check out the current gatekeeper-library, copy the files manually to the argocd app and have a look from time to time to stay up-to-date and do the manual checkout again.

I'm not sure how the releasing could be achieved. Maybe release-branches could be a way to achieve the releasing.
A Kubernetes-YAML like the installation YAML for Gatekeeper will not make it possible to choose which libraries should be installed and which not.

Maybe some has a better idea.

**Comment by maxsmythe** [comment]
The library is probably a better candidate for semver versioning than most, as its interface is pretty well defined.

Another option could be to fork the repo and point ArgoCD at the fork, downstreaming updates when it makes sense to do so.

**Comment by estahn** [comment]
@FabiusE As a workaround, you could use the Git SHA to pin to a specific commit.
