### ISSUE TITLE
runAsNonRoot SecurityContext

### ISSUE THREAD

**Issue by sanderma** [open-policy-agent/gatekeeper-library#49]
The [psp users rule](https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/pod-security-policy/users/src.rego) checks `runAsUser`, but ignores the `runAsNonRoot` SecurityContext.
Is there a specific reason for this?

I'd expect that if a user provides `runAsNonRoot` and leaves the `runAsUser` out, the review object is not denied.
In that case the kubelet will ensure that the image doesn't run as root.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-disallowed
  labels:
    app: nginx-users
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: nginx
      image: nginx
```

`kubectl describe pod -l app=nginx-users`

```
Normal   Pulling                 2s (x2 over 10s)    kubelet            Pulling image "nginx"
Warning  Failed                  2s                  kubelet            Error: container has runAsNonRoot and image will run as root
Normal   Pulled                  0s (x2 over 2s)     kubelet            Successfully pulled image "nginx"
```

I changed the rule a bit so when you set `MustRunAsNonRoot` it also allows setting the `securityContext/runAsNonRoot`:

```rego
# RunAsUser (separate due to "MustRunAsNonRoot")
get_user_violation(params, container) = msg {
  rule := params.rule
  provided_user := get_field_value("runAsUser", container, input.review)
  not accept_users(rule, provided_user)
  msg := sprintf("Container %v is attempting to run as disallowed user %v. Allowed runAsUser: %v", [container.name, provided_user, params])
}

get_user_violation(params, container) = msg {
  not get_field_value("runAsUser", container, input.review)
  not get_field_value("runAsNonRoot", container, input.review)
  params.rule != "RunAsAny"
  params.rule != "runAsNonRoot"
  msg := sprintf("Container %v is attempting to run without a required securityContext/%v", [container.name, params.rule])
}

get_user_violation(params, container) = msg {
  params.rule = "runAsNonRoot"
  not get_field_value("runAsUser", container, input.review)
  not get_field_value("runAsNonRoot", container, input.review)
  msg := sprintf("Container %v is attempting to run without a required securityContext/runAsNonRoot or securityContext/runAsUser != 0", [container.name])
}
```

Am I missing something, or should I do  a PR with this change (and added tests)? @

**Comment by maxsmythe** [comment]
What is the behavior of Pod Security Policy for `runAsUser`?

https://kubernetes.io/docs/concepts/policy/pod-security-policy/

These templates were designed to map as close to PSP as is reasonable in order to simplify migration, so this template should try to replicate that behavior.

I will say "not running as root" and "running as a specific user" could have very different implications depending on the infrastructure. Because "run as non-root" is more permissive, it probably deserves its own dedicated template.

It may be reasonable for that separate template to allow either the "runAsNonRoot" directive or for the config to supply a specific (non-zero) user, as either wouldn't be root.

**Comment by sanderma** [comment]
The [doc](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups) tells us this:

> MustRunAsNonRoot - Requires that the pod be submitted with a non-zero runAsUser or have the USER directive defined (using a numeric UID) in the image.

So in that regard I'd say that it is valid to set the securityContext runAsNonRoot as that will ensure UID != 0 without having to specify the runAsUser in the securityContext.

The rule as is makes it incompatible with the psp, as the psp doesn't require you to set the runAsUser securityContext but the rego does.

In that case it should be in this template right? WDYT?

**Comment by EmandM** [comment]
> MustRunAsNonRoot - Requires that the pod be submitted with a non-zero runAsUser or have the USER directive defined (using a numeric UID) in the image. **Pods which have specified neither runAsNonRoot nor runAsUser settings will be mutated to set runAsNonRoot=true**, thus requiring a defined non-zero numeric USER directive in the container. No default provided. 
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups

It looks like the PSP does recognise the `runAsNonRoot` flag, and uses it during mutations. I think this is a good change to make

**Comment by maxsmythe** [comment]
That excerpt is on point, for sure.

It looks like PSP allows a `RunAsUser` set to `MustRunAsNonRoot`. Should we add that option?

That would both match what PSP does and avoids retroactively weakening the constraint template's enforcement profile for pre-existing implementations.

Not 100% sure what that parameter would look like. A bool seems easiest, but is discouraged by K8s conventions. OTOH I don't think an enum would make sense.

**Comment by sanderma** [comment]
The params.rule `runAsNonRoot` is already present in the current rego. The only downside is that is checks for a runAsUser field.
The only addition in this case is to check for the `runAsNonRoot` securityContext.

**Comment by maxsmythe** [comment]
Ah, perfect. This change makes total sense then.

**Comment by sanderma** [comment]
Good to hear!

I can do a PR with the change and added tests. I need to refactor some existing tests, so I expect this to be ready in the next few days.
