### ISSUE TITLE
Example of pod mutation adding init-container 

### ISSUE THREAD

**Issue by oreillymj** [open-policy-agent/gatekeeper-library#492]
I've looked at the example of modifying a pod spec to add capabilities.

mutation/pod-security-policy/capabilities/samples/mutation-modifyset.yaml

Is it possible to modify a pod-spec to add an init-container to all pods in all namespaces except kube-system

**Comment by ritazh** [comment]
PTAL https://open-policy-agent.github.io/gatekeeper/website/docs/mutation#adding-a-network-sidecar-to-a-pod you can replace container with initContainer

**Comment by oreillymj** [comment]
Thank you for the pointer. I see the policy is namespaced, can you apply to all namespaces excluding certain namespaces such as kube-system

**Comment by maxsmythe** [comment]
Linked example will apply to all namespaces. "Namespaced" in the example means "only apply to namespaced resources"
