### ISSUE TITLE
poddisruptionbudget policy query

### ISSUE THREAD

**Issue by pankajmt** [open-policy-agent/gatekeeper-library#510]
From our additional rego tests, looks like community `poddisruptionbudget` policy works for the case where PDB selects on less labels than say what a Deployment has. Which is good. But not sure how this code does the job and I have not been able to disprove it does not work as intended!

[Permalink](https://github.com/open-policy-agent/gatekeeper-library/blob/5a5cd361b484e6d0e94112529e192899a583b049/src/general/poddisruptionbudget/src.rego#L18)
```
matchLabels := { [label, value] | some label; value := pdb.spec.selector.matchLabels[label] }
  labels := { [label, value] | some label; value := obj.spec.selector.matchLabels[label] }
  count(matchLabels - labels) == 0
```

Thoughts?

**Comment by pankajmt** [comment]
@pankajmt check check

**Comment by maxsmythe** [comment]
Sorry for the slow reply.

It's creating two sets of <label, value> tuples. It takes the "matchLabels" set and subtracts out the "object labels" set. If there is no remainder, then the three statements are all "truthy" (the rule continues to be processed).

Basically, as long as `labels` is equal to (or a super set of) matchLabels, they will be considered a match.

**Comment by pankajmt** [comment]
many thanks for the explanation. and i got to this only now :)
