### ISSUE TITLE
PodDisruptionBudget check

### ISSUE THREAD

**Issue by kfox1111** [open-policy-agent/gatekeeper-library#52]
An issue I've hit a few times that would be really nice to have a library for,
PodDisruptionBudgets with minAvailable: 1 and a Deployment with replicas = 1.

This really messes with node drains. Its a valid config for some clusters but in a multi-tenant environment, not so much.

**Comment by s-spindler** [comment]
I'd be very interested in this as well. @kfox1111 have you found a workaround?

**Comment by kfox1111** [comment]
no, sorry. completely fell off my radar.

https://open-policy-agent.github.io/gatekeeper/website/docs/sync/ might be useful for helping solve it.

**Comment by chewong** [comment]
I can take a look at this issue if no one is working on it 😄

**Comment by crowean** [comment]
> I can take a look at this issue if no one is working on it smile
If you have time, Could you take a look this link? 
https://github.com/open-policy-agent/community/discussions/69?sort=old#discussion-3694177

**Comment by maxsmythe** [comment]
As in, if a deployment has an owner reference, ignore the check?

Is there any risk of a user using this exception maliciously, such as by setting a false owner reference? It could reference a real K8s object, but the object could just not be managing the resource-under-test.

**Comment by kfox1111** [comment]
Yeah. I don't think there's a way to deal with malicious in this context. There's probably quite a few ways besides just owner references to still make pdb's that block rolling upgrades. I think this check is probably useful just to try and prevent accidental configurations that block rolling upgrades.

**Comment by maxsmythe** [comment]
If we want to selectively disable it for certain services, would using match criteria be a better fit for that? It would leave more flexibility for configuration on the user's end.
