### ISSUE TITLE
provide docs for K8s PSP to Gatekeeper policy adoption

### ISSUE THREAD

**Issue by sozercan** [open-policy-agent/gatekeeper-library#56]
Provide docs on how users can adopt GK PSP equivalent policies

**Comment by JaveriaK** [comment]
Please also add some more detail around what the behavior is for policies implemented by both PSP and Gatekeeper constraints in the same cluster. Is it ok to run both of these policy enforcement validation webhooks simultaneously? When both get called is there a precedence or race condition?
