### ISSUE TITLE
mustRunAsNonRoot evaluations will error out in some cases

### ISSUE THREAD

**Issue by wc-s** [open-policy-agent/gatekeeper-library#60]
This can be reproduced by adding this test to https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/pod-security-policy/users/src_test.rego

```
test_wcs {
  input := {"review": review({"runAsNonRoot": true}, [ctr("cont1", runAsNonRoot(false))], null), "parameters": user_mustrunasnonroot }
  results := violation with input as input
  count(results) == 0
}
```

You should see: 
```
data.k8spspallowedusers.test_wcs: ERROR (1.205236ms)
  /opa-policies/src.rego:90: eval_conflict_error: functions must not produce multiple outputs for same inputs
```

The review object isn't anything too special, just a Pod with PodSecurityContext setting runAsNonRoot=true, but with a container overriding that.

The error is triggered by this line in the policy code: https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/pod-security-policy/users/src.rego#L39

It will run the functions on both L84 and L90, and will obtain different results from them (false and true, respectively).

The root of the problem is probably that L91 is not a good enough guard. The function on L90 will trigger not only when "no container level field exists", it will also trigger when "the container level field exists but is set to false".

**Comment by maxsmythe** [comment]
Thank you for finding this!

**Comment by wc-s** [comment]
No problem, thanks for fixing!
