### ISSUE TITLE
Is gatekeeper-policy namespace is mandate?

### ISSUE THREAD

**Issue by Rishikeshpal** [open-policy-agent/gatekeeper-library#67]
Is gatekeeper-policy namespace is mandate?
i am using helm for gatekeeper-policy which has templates and constraints which has been inhouse developed. 
Its not a bug BUT more like a generic question, if the gatekeeper-policy namespace needs to be created first.
I tried to install it and it errored out with gatekeeper-polcy namespace not found. so i created it and it worked.
is there any documentation for this?

**Comment by ritazh** [comment]
Both constraint templates and constraints are currently cluster-scoped. There's no requirement to create any namespace for the sample policies in this repo.

**Comment by Rishikeshpal** [comment]
thank you for the information.
