### ISSUE TITLE
excludedNamespaces with wildcard for gatekeeper constraint object

### ISSUE THREAD

**Issue by igorkchyts** [open-policy-agent/gatekeeper-library#69]
I want to apply the constraint on every pod that is not in 'openshift-*' namespace.
The constraint that I tried:

```apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHostNamespaces
metadata:
  name: k8s-host-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - openshift-*
```

Also tried:

```apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHostNamespaces
metadata:
  name: k8s-host-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["openshift-*"]
```

The result is that Openshift namespaces are still affected under this constraint. If exclude the namespaces specifically like 'openshift-etcd' or 'openshift-image-registry' then the namespaces will not fall under the constraint as expected. 

Expected results: Be able to include wildcard for spec.match.excludedNamespaces field in gatekeeper constraints.

**Comment by shomron** [comment]
@igorkchyts thanks for reporting. This is on our radar and is tracked in open-policy-agent/gatekeeper#500.

**Comment by maxsmythe** [comment]
closing as a duplicate. Please re-open if I'm missing something.
