### ISSUE TITLE
Image Content Signature Check Policy

### ISSUE THREAD

**Issue by developer-guy** [open-policy-agent/gatekeeper-library#71]
This topic is really hot these days, so, If such support can be added to the library, it would be great!

There is a very great blog post available on this area, from Maximilian Siegert, you can refer to this [`link`](https://medium.com/@siegert.maximilian/ensure-content-trust-on-kubernetes-using-notary-and-open-policy-agent-485ab3a9423c) to the blog post.

But the main rego file for the image content signature check is just a few line codes:
https://gist.github.com/Igelchen1/e60a00f0da8f3b040b0bcf0fb1ca16da#file-main-rego

But this sample is using [`Notary`](https://github.com/theupdateframework/notary), but a new project called _cosign_ is now available, so, we can enhance the policy to be able to use [`cosign`](https://github.com/sigstore/cosign) too.

Wdyt?

**Comment by ritazh** [comment]
+1 Would be great to have an example of this use case in this library once we have external data support working together with mutation. 

We actually added this image signature scenario to [the external design doc](https://docs.google.com/document/d/1hPi86jdsCKg8puYT5_s_73mPGExUJeZfyKmvG-XWtPc/edit#heading=h.s5ci3gr3qj2z), please take a look.

**Comment by sozercan** [comment]
This is completed with external data providers like ratify: https://open-policy-agent.github.io/gatekeeper/website/docs/externaldata#providers-maintained-by-the-community
