### ISSUE TITLE
using `startwith` in allowedrepos policy may allow for bypass

### ISSUE THREAD

**Issue by raesene** [open-policy-agent/gatekeeper-library#80]
The [Allowed Repos policy](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/allowedrepos/template.yaml) checks that containers are from approved locations.

It uses startswith as a function to conduct [this check](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/allowedrepos/template.yaml#L28).

Taking this approach could allow for bypass as an attacker could just start their image name with one of the approved strings.

As shown in [this example ](https://play.openpolicyagent.org/p/iHgFVrQu08) where the allowed string is "openpolicyagent" , "openpolicyagentnotreally" will be allowed.

Using an approach which matches the whole account name or other string, would help mitigate this kind of risk.

**Comment by ritazh** [comment]
@raesene in your constraint resource, you can add a trailing `/` to your repos parameter. 

e.g:
```yaml
  parameters:
    repos:
      - "openpolicyagent/"
```

**Comment by raesene** [comment]
Yep anchoring might be useful here. I was basing the problem on the sample constraint https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/allowedrepos/samples/repo-must-be-openpolicyagent/constraint.yaml that's included with the rule, which doesn't anchor to a / character.

Might be worth updating the sample so it shows that as an example :)

**Comment by maxsmythe** [comment]
Good point, created #81 to address
