### ISSUE TITLE
Provided Uniqueingresshost constrainttemplaete/constraint doesn't work

### ISSUE THREAD

**Issue by vkumar3891** [open-policy-agent/gatekeeper-library#83]
I have tried using the Uniqueingresshost library **ref: https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/uniqueingresshost**  on the GCP- GKE cluster where I have my Anthos config management and Policy controller is installed with the latest version.(Having Gatekeeper installed) 

I see the provided Uniqueingresshost library (constrainttemplate/constraint) doesn't work as expected. ingress-hosts were being created without being disallowed to create or restricting them to create as per the functionality to allow only a unique ingress host.

I have tried using the same approach for creating a Virtualservice-constrainttemplate & constraint where they need to check the resource if it is already created or using the host and it needs to restrict creating a virtual service when there is already a virtual service that uses the same host name. 

used constrainttemplate- posting :
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8svirtualserviceuniquehostmatchnew
spec:
  crd:
    spec:
      names:
        kind: K8sVirtualServiceUniqueHostMatchNew
  targets:
    - target: admission.k8s.gatekeeper.sh
  
      rego: |
        package k8svirtualserviceuniquehostmatchnew

        identical(obj, review) {
          obj.metadata.namespace == review.object.metadata.namespace
          obj.metadata.name == review.object.metadata.name
        }

        violation[{"msg": msg}] {
          input.review.kind.kind == "VirtualService"
          re_match("^(extensions|networking.k8s.io)$", input.review.kind.group)
          host := input.review.object.spec.hosts[_]
          other := data.inventory.namespace[ns][otherapiversion]["VirtualService"][name].spec.hosts[_]
          re_match("^(extensions|networking.k8s.io)/.+$", otherapiversion)
          other.spec.hosts[_] == host
          not other == host
          not identical(other, input.review)
          msg := sprintf("ingress host conflicts with an existing ingress <%v>", [host])
        }

## Trying to create a Virtualservice constrainttemplae/constraint which allows creating a virtualservice with a unique host on the same namespace and restricts the which have the same host.

#Gatekeeper version: Image:       gcr.io/config-management-release/gatekeeper:anthos1.6.2-6dd505e.g0
Kubernetes version: v1.20.4

**Comment by maxsmythe** [comment]
The following support document may be helpful:

https://cloud.google.com/anthos-config-management/docs/how-to/creating-constraints#gatekeeper-config

Because this is a vendor-specific flavor of Gatekeeper, please reach out to the vendor directly for support.
